---
# Create repo for vSDE install
- name: Install certs/sde repo
  expect:
    command: svrepo
    echo: yes
    responses:
      'Download and install now? [n]|y:': 'y'
      'Email Address:': "{{ username }}"
      'Password     :': "{{ password }}"
      '\r\n\r\nEnter quit/1-15:': '10'
      '\r\n\r\nEnter quit/1-3:': '3'
      '\r\n\r\nEnter quit/1-1': '1'
      'Run': 'y'
  no_log: true
