---
# Usage --> ansible-playbook Install_vSDE.yaml --extra-vars "username=<username_here> password=<pwd_here>"
  - hosts: sde
    remote_user: root
    become: yes
    tasks:
      - name: Disable selinux
        selinux:
          state: disabled

    #First Update Yum and install dependencies for what we need (disabled for now)
      - name: Install the 'Base' package group
        yum:
          name: "@Base"
          state: present
      - name: Upgrade all packages
        yum:
          name: '*'
          state: latest
      - name: Install createrepo (for svbootstrap)
        yum:
          name: createrepo
          state: present
      - name: Install epel
        yum:
          name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
          state: latest
      - name: Install wget
        yum:
          name: wget
          state: present
      - name: Install nginx
        yum:
          name: nginx
          state: present
      - name: Install pip
        yum:
          name: python-pip
          state: present
      - name: Install pexpect
        pip:
          name: pexpect
        become: yes
      - name: Download and Install svrepo/svbootstrap
        yum:
          name: "https://files.support.sandvine.com/public/svbootstrap/svbootstrap.el7.x86_64.rpm"
          state: latest
      - name: Install certs/sde repo
        expect:
          command: svrepo
          echo: yes
          responses:
            'Download and install now? [n]|y:': 'y'
            'Email Address:': "{{ username }}"
            'Password     :': "{{ password }}"
            'Enter quit/1-15:': '10'
            'Enter quit/1-3:': '3'
            'Enter quit/1-1': '1'
            'Run': 'y'
        no_log: true

      # Install SDE here
      - name: Install sde packages
        yum:
          name: sde
          state: present
        notify:
        - restartsde
      - name: Restart service sde
        service:
          name: sde
          state: restarted
    handlers:
    - name: restartsde
      service:
        name: sde
        state: restarted
