---
# Usage --> ansible-playbook Install_vSPB.yaml --extra-vars "username=<username_here> password=<pwd_here>"
  - hosts: spb
    remote_user: root
    become: yes
    tasks:
      - name: Disable selinux
        selinux:
          state: disabled

    #First Update Yum and install dependencies for what we need
      - name: Install the 'Base' package group
        yum:
          name: "@Base"
          state: present
      - name: Upgrade all packages
        yum:
          name: '*'
          state: latest
      - name: Install SPB Base Dependencies
        ignore_errors: yes
        yum:
          name: "{{ pkg }}"
          state: latest
        vars:
          pkg:
          - at
          - bc
          - gdb
          - glibc
          - ncurses-libs
          - nss-softokn-freebl
          - procmail
          - net-snmp
          - net-snmp-utils
          - stunnel
          - dmidecode
          - java-1.7.0-openjdk
      - name: Install PostgreSQL Repo
        yum:
          name: "https://download.postgresql.org/pub/repos/yum/9.3/redhat/rhel-7-x86_64/pgdg-centos93-9.3-3.noarch.rpm"
          state: latest
      - name: Install PostgreSQL 9.3 server packages
        yum:
          name: "{{ packages }}"
          state: latest
        vars:
          packages:
          - postgresql93-server
          - postgresql93-contrib
          - postgresql93-odbc
      - name: Install createrepo (for svbootstrap)
        yum:
          name: createrepo
          state: present
      - name: Install epel
        yum:
          name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
          state: latest
      - name: Install wget
        yum:
          name: wget
          state: present
      - name: Install pip
        yum:
          name: python-pip
          state: present
      - name: Install pexpect
        pip:
          name: pexpect
        become: yes
      - name: Download and Install svrepo/svbootstrap
        yum:
          name: "https://files.support.sandvine.com/public/svbootstrap/svbootstrap.el7.x86_64.rpm"
          state: latest
      - name: Install certs/spb repo
        expect:
          command: svrepo
          echo: yes
          responses:
            'Download and install now? [n]|y:': 'y'
            'Email Address:': "{{ username }}"
            'Password     :': "{{ password }}"
            '\r\n\r\nEnter quit/1-15:': '11'
            'Enter quit/1-2': '2'
            'Enter quit/1-3': '3'
            'Enter quit/1-1': '1'
            'Run': 'y'
        no_log: true

      # Install SPB here
      - name: Install spb packages
        yum:
          name: svspb
          state: present
        notify:
        - restartspb
      - name: Starting PostgreSQL on Boot
        command: chkconfig postgresql-9.3 on
        register: output
      # Use loop to Restart SPB services
      - name: Start SPB services
        systemd:
          name: "{{ item }}"
          state: started
        with_items:
          - 'servicelauncher'
          - 'scdpd'
          - 'msd'
          - 'appsrv'
          - 'msgsrv'
          - 'postgresql-9.3'
    handlers:
    - name: restartspb
      command: svreload
      register: output
