---
  - hosts: pts spb
    remote_user: root
    become: yes
    with_items:
      - 'pts'
      - 'spb'
    tasks:
      - name: Download and Install svrepo/svbootstrap
        yum:
          name: "https://files.support.sandvine.com/public/svbootstrap/svbootstrap.el7.x86_64.rpm"
          state: latest
      # Protocols are in the same Menu postion for PTS and SPB at least
      - name: Install certs/pts repo
        expect:
          command: svrepo
          echo: yes
          responses:
            'Download and install now? [n]|y:': 'y'
            'Email Address:': "{{ username }}"
            'Password     :': "{{ password }}"
            '\r\n\r\nEnter quit/1-15:': '9'
            '\r\n\r\nEnter quit/1-1:': '1'
            '\r\n\r\nEnter quit/1-3:': '3'
            '\r\n\r\nEnter quit/1-2:': '2'
            "Run 'yum clean all' now?": 'y'
        no_log: false

# Upgrade virtual PTS devices
    tasks:
      - name: Upgrade vPTS LTIP
        yum:
          name: svprotocols
          state: latest
          when: hosts == 'pts'

# Upgrade SPB devices
    tasks:
      - name: Upgrade vSPB packages
        yum:
          name: "{{ packages }}"
          state: latest
        vars:
          packages:
          - svprotocols-version
          - svprotocols-nds
          when: hosts == 'spb'
