---
  - hosts: pts:spb
    remote_user: root
    become: yes
    gather_facts: yes
    tasks:
      - name: Download and Install svrepo/svbootstrap
        yum:
          name: "https://files.support.sandvine.com/public/svbootstrap/svbootstrap.el7.x86_64.rpm"
          state: latest
      # Protocols are in the same Menu postion for PTS and SPB at least
      - name: Install certs/pts repo
        expect:
          command: svrepo
          echo: yes
          responses:
            'Download and install now? [n]|y:': 'y'
            'Email Address:': "{{ username }}"
            'Password     :': "{{ password }}"
            '\r\n\r\nEnter quit/1-15:': '9'
            '\r\n\r\nEnter quit/1-1:': '1'
            '\r\n\r\nEnter quit/1-3:': '3'
            '\r\n\r\nEnter quit/1-2:': '2'
            "Run 'yum clean all' now?": 'y'
        no_log: false

# Upgrade virtual PTS devices
      - name: Upgrade vPTS LTIP
        when: ansible_hostname == "labpts"
        yum:
          name: svprotocols
          state: latest

# Upgrade SPB devices
      - name: Upgrade vSPB LTIP
        when: ansible_hostname == "labspb"
        yum:
          name: "{{ packages }}"
          state: latest
        vars:
          packages:
          - svprotocols-version
          - svprotocols-nds
