---
# Create repo for vPTS install
- name: Install certs/spb repo
  expect:
    command: svrepo
    echo: yes
    responses:
      'Download and install now? [n]|y:': 'y'
      'Email Address:': "{{ svrepo_username }}"
      'Password     :': "{{ svrepo_password }}"
      '\r\n\r\nEnter quit/1-15:': '11'
      '\r\n\r\nEnter quit/1-2': '2'
      '\r\n\r\nEnter quit/1-3': '3'
      '\r\n\r\nEnter quit/1-1': '1'
      'Run': 'y'
  no_log: true
