---
# Use loop to Restart SPB services
- name: Start SPB services
  systemd:
    name: "{{ item }}"
    state: started
  with_items:
    - 'servicelauncher'
    - 'scdpd'
    - 'msd'
    - 'appsrv'
    - 'msgsrv'
    - 'postgresql-9.3'
    - 'svprocmon'
    - 'configuration'
    - 'nginx'
    - 'svspbmd'
    - 'svpamd'
    - 'consul'
- name: svreload for good measure
  command: svreload
  register: output
