---
# Usage --> ansible-playbook Install_vPTS.yaml --extra-vars "username=<username_here> password=<pwd_here>"
  - hosts: svpts
    remote_user: root
    become: yes
    tasks:
      - name: Disable selinux
        selinux:
          state: disabled

    #First Update Yum and install dependencies for what we need (disabled for now)
      # - name: upgrade all packages
      #   yum:
      #     name: '*'
      #     state: latest
      - name: install createrepo (for svbootstrap)
        yum:
          name: createrepo
          state: present      
      - name: install epel
        yum:
          name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
          state: latest
      - name: install wget
        yum:
          name: wget
          state: present
      - name: install pip
        yum:
          name: python-pip
          state: present
      - name: install pexpect
        pip:
          name: pexpect
        become: yes    
      - name: Download svbootstrap
        yum:
          name: "https://files.support.sandvine.com/public/svbootstrap/svbootstrap.el7.x86_64.rpm"
          state: latest      
      - name: install certs/pts repo
        expect:
          command: svrepo
          echo: yes
          responses:
            'Download and install now? [n]|y:': 'y'
            'Email Address:': "{{ username }}"
            'Password     :': "{{ password }}"
            'Enter quit/1-15:': '8'
            'Enter quit/1-3:': '3'
            'Enter quit/1-1': '1'
            'Run': 'y'
        no_log: true

      - name: install svpts packages
        block:
          - yum:
              name: svpts
              state: present
        rescue:
          - debug:
              msg: "There was an issue installing so lets try install openssl and perl-WWW-curl"
          - name: Installing perl-WWW-curl
            yum:
              name: "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-WWW-Curl-4.15-13.el7.x86_64.rpm"
              state: latest
          - name: Installing openssl-perl due to above failure
            yum:
              name: "http://mirror.centos.org/centos/7/os/x86_64/Packages/openssl-perl-1.0.2k-16.el7.x86_64.rpm"
              state: latest
      - name: Try install svpts Again! No More errors :)
        yum:
          name: svpts
          state: present
      # - name: Restart services
      #   command: service svsde restart
      #   register: output