---
# Usage --> ansible-playbook Install_vspb.yaml --extra-vars "username=<username_here> password=<pwd_here>"
  - hosts: spb
    remote_user: root
    become: yes
    tasks:
      - name: Disable selinux
        selinux:
          state: disabled

    #First Update Yum and install dependencies for what we need (disabled for now)
      # - name: upgrade all packages
      #   yum:
      #     name: '*'
      #     state: latest
      - name: install epel
        yum:
          name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
          state: latest
      - name: install wget
        yum:
          name: wget
          state: present
      - name: install nginx
        yum:
          name: nginx
          state: present
      - name: install pip
        yum:
          name: python-pip
          state: present
      - name: install pexpect
        pip:
          name: pexpect
        become: yes    
      - name: Download svbootstrap
        get_url:
          url: https://files.support.sandvine.com/public/svbootstrap/svbootstrap.el7.x86_64.rpm
          dest: /opt/svbootstrap.el7.x86_64.rpm
      - name: Install svbootstrap
        shell: rpm -Uvh svbootstrap.el7.x86_64.rpm
        args:
          chdir: /opt/

      # Once downloaded and installed lets install the certs
      - name: install certs/spb repo
        expect:
          command: svrepo
          echo: yes
          responses:
            'Download and install now? [n]|y:': 'y'
            'Email Address:': "{{ username }}"
            'Password     :': "{{ password }}"
            'Enter quit/1-15:': '11'
            'Enter quit/1-2': '2'
            'Enter quit/1-3:': '3'
            'Enter quit/1-1': '1'
            'Run': 'y'
        no_log: true

      - name: install spb packages
        yum:
          name: svspb
          state: present
        notify:
        - restart spb service for good measure
    handlers:
      - name: restart spb service for good measure
        service:
          name: svspb
          enabled: yes
          state: restarted

      #   rescue:
      #     - debug:
      #         msg: "There was an issue installing so lets try install openssl and perl-WWW-curl"
      #     - name: Installing perl-WWW-curl
      #       get_url:
      #         url: http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-WWW-Curl-4.15-13.el7.x86_64.rpm
      #         dest: /opt/perl-WWW-Curl-4.15-13.el7.x86_64.rpm
      #     - name: Install the package perl-WWW-curl
      #       shell: rpm -Uvh perl-WWW-Curl-4.15-13.el7.x86_64.rpm
      #       args:
      #         chdir: /opt/
      #     - name: Installing openssl-perl due to above failure
      #       get_url:
      #         url: http://mirror.centos.org/centos/7/os/x86_64/Packages/openssl-perl-1.0.2k-16.el7.x86_64.rpm
      #         dest: /opt/openssl-perl-1.0.2k-16.el7.x86_64.rpm
      #     - name: Install the package openssl-perl
      #       shell: rpm -Uvh openssl-perl-1.0.2k-16.el7.x86_64.rpm
      #       args:
      #         chdir: /opt/
      # - name: Try install spb Again! No More errors :)
      #   yum:
      #     name: spb
      #     state: present
      # - name: Restart services
      #   command: service spb restart
      #   register: output